version: '3.8'

services:

  api:
    build: 
      context: .
      dockerfile: Dockerfile
    container_name: mundolog-api
    ports:
      - 8080:8080
    depends_on:
      - db
  
  db:
    image: mysql:8.0.22
    container_name: db
    ports:
      - 3309:3306
    environment:
      MYSQL_USER: mundolog
      MYSQL_PASSWORD: mundolog
      MYSQL_ROOT_PASSWORD: mundolog
      MYSQL_DATABASE: mundolog
